JustEat Proyecto Final Programado: Capa_Entidades.Clases.Factura Class Reference
Capa_Entidades.Clases.Factura Class Reference
Clase Factura, se encarga de elaborar el PDF y XML que seran enviados por correo
Public Member Functions
Factura ()
Constructor de clase, sin recibir parametros
void AsignaCliente (Usuario pCliente)
Metodo AsignaCliente, asigna el Cliente
void AsignaPagoCliente (Pago pPago)
Metodo AsignaCliente, asigna el Pago
void AsignaComercio (Usuario pComercio)
Metodo AsignaCliente, asigna el Comercio
double CalculaMonto_Total ()
Metodo CalculaMonto_Total, calcula el total de la factura
double CalculaMonto_Total_SoloConIVA ()
Metodo CalculaMonto_Total_SoloConIVA, calcula el total de la factura
double CalculaMonto_Total_Dolares ()
Metodo CalculaMonto_Total_Dolares, calcula el total de la factura en dolares
double CalculaMonto_Total_SinEnvio ()
Metodo CalculaMonto_Total_SinEnvio, calcula el total de la factura sin el envio
double CalculaMonto_Cupones ()
Metodo CalculaMonto_Cupones, calcula el total de dinero por los cupones
double CalculaMonto_Productos ()
Metodo CalculaMonto_Productos, calcula el total de dinero por los productos
double Calcula_IVA ()
Metodo Calcula_IVA, calcula el IVA
double Calcula_SubTotal ()
Metodo Calcula_SubTotal, calcula monto sin IVA
double Calcula_SubTotal_Gravado ()
double Calcula_Envio ()
Metodo Calcula_Envio, calcula coste del envio
string ObtenerXML ()
Metodo que genera el XML de Factura
void ObtenerPDF ()
Metodo que genera el PDF de Factura
void ObtenerPDF_GuardadoEnRutaSeleccionada (string pRuta)
Metodo que genera el PDF de Factura, y lo guarda en la ruta especificada por el usuario
void SetCulture ()
Metodo que setea la cultura de la clase
Public Attributes
Usuario _UsuarioCliente = null
_UsuarioCliente
Pago _PagoUsuarioCliente = null
_PagoUsuarioCliente
Usuario _UsuarioComercio = null
_UsuarioComercio
Private Member Functions
void AgregaImagenPDF (Document objPdfDocument, string strFileImage)
Metodo que agrega una imagen/slogan al PDF creado
Detailed Description
Clase Factura, se encarga de elaborar el PDF y XML que seran enviados por correo
Definition at line 21 of file Factura.cs.
Constructor & Destructor Documentation
Factura()
Capa_Entidades.Clases.Factura.Factura ()
Constructor de clase, sin recibir parametros
Definition at line 40 of file Factura.cs.
         {
             this._UsuarioCliente = null;
             this._PagoUsuarioCliente = null;
             this._UsuarioComercio = null;
         }
Member Function Documentation
AgregaImagenPDF()
void Capa_Entidades.Clases.Factura.AgregaImagenPDF (Document objPdfDocument, string strFileImage) private
Metodo que agrega una imagen/slogan al PDF creado
Returns
void
Definition at line 928 of file Factura.cs.
         {
             iTextSharp.text.Image objImagePdf;
             //    Crea la imagen
             objImagePdf = iTextSharp.text.Image.GetInstance(strFileImage);
             // Cambia el tamaño de la imagen
             objImagePdf.ScaleToFit(64, 64);
             // Se indica que la imagen debe almacenarse como fondo
             objImagePdf.Alignment = iTextSharp.text.Image.ALIGN_RIGHT;
             // Coloca la imagen en una posición absoluta
             objImagePdf.SetAbsolutePosition(500, 700);
             objPdfDocument.Add(objImagePdf);
         }
Referenced by Capa_Entidades.Clases.Factura.ObtenerPDF(), and Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada().
AsignaCliente()
void Capa_Entidades.Clases.Factura.AsignaCliente (Usuario pCliente)
Metodo AsignaCliente, asigna el Cliente
Returns
void
Definition at line 52 of file Factura.cs.
         {
             this._UsuarioCliente = pCliente;
         }
AsignaComercio()
void Capa_Entidades.Clases.Factura.AsignaComercio (Usuario pComercio)
Metodo AsignaCliente, asigna el Comercio
Returns
void
Definition at line 70 of file Factura.cs.
         {
             this._UsuarioComercio = pComercio;
         }
Referenced by Capa_Entidades.Gestor.Gestor_Factura.AsignaComercio().
AsignaPagoCliente()
void Capa_Entidades.Clases.Factura.AsignaPagoCliente (Pago pPago)
Metodo AsignaCliente, asigna el Pago
Returns
void
Definition at line 61 of file Factura.cs.
         {
             this._PagoUsuarioCliente = pPago;
         }
Referenced by Capa_Entidades.Gestor.Gestor_Factura.AsignaPagoCliente().
Calcula_Envio()
double Capa_Entidades.Clases.Factura.Calcula_Envio ()
Metodo Calcula_Envio, calcula coste del envio
Returns
double
Definition at line 184 of file Factura.cs.
         {
             return _PagoUsuarioCliente.CostoExpressColones();
         }
References Capa_Entidades.Clases.Factura._PagoUsuarioCliente, and Capa_Entidades.Clases.Pago.CostoExpressColones().
Referenced by Capa_Entidades.Gestor.Gestor_Factura.Calcula_Envio(), Capa_Entidades.Clases.Factura.Calcula_SubTotal(), Capa_Entidades.Clases.Factura.ObtenerPDF(), Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Clases.Factura.ObtenerXML().
Calcula_IVA()
double Capa_Entidades.Clases.Factura.Calcula_IVA ()
Metodo Calcula_IVA, calcula el IVA
Returns
double
Definition at line 151 of file Factura.cs.
         {
             return Calcula_SubTotal() * .13;
         }
References Capa_Entidades.Clases.Factura.Calcula_SubTotal().
Referenced by Capa_Entidades.Gestor.Gestor_Factura.Calcula_IVA(), Capa_Entidades.Clases.Factura.CalculaMonto_Total(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_Dolares(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_SinEnvio(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_SoloConIVA(), Capa_Entidades.Clases.Factura.ObtenerPDF(), Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Clases.Factura.ObtenerXML().
Calcula_SubTotal()
double Capa_Entidades.Clases.Factura.Calcula_SubTotal ()
Metodo Calcula_SubTotal, calcula monto sin IVA
Returns
double
Definition at line 160 of file Factura.cs.
         {
             double sumatoria = 0.0;
             foreach(Articulo item in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
             {
                 sumatoria += item.Precio;
             }
             return sumatoria + Calcula_Envio();
         }
References Capa_Entidades.Clases.Pedido._ListaArticulosComprados, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Pago._Pedido, Capa_Entidades.Clases.Factura.Calcula_Envio(), and Capa_Entidades.Clases.Articulo.Precio.
Referenced by Capa_Entidades.Clases.Factura.Calcula_IVA(), Capa_Entidades.Gestor.Gestor_Factura.Calcula_SubTotal(), Capa_Entidades.Clases.Factura.CalculaMonto_Total(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_Dolares(), and Capa_Entidades.Clases.Factura.ObtenerXML().
Calcula_SubTotal_Gravado()
double Capa_Entidades.Clases.Factura.Calcula_SubTotal_Gravado ()
Definition at line 170 of file Factura.cs.
         {
             double sumatoria = 0.0;
             foreach (Articulo item in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
             {
                 sumatoria += item.Precio;
             }
             return sumatoria ;
         }
References Capa_Entidades.Clases.Pedido._ListaArticulosComprados, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Pago._Pedido, and Capa_Entidades.Clases.Articulo.Precio.
Referenced by Capa_Entidades.Clases.Factura.CalculaMonto_Total_SinEnvio(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_SoloConIVA(), Capa_Entidades.Clases.Factura.ObtenerPDF(), Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Clases.Factura.ObtenerXML().
CalculaMonto_Cupones()
double Capa_Entidades.Clases.Factura.CalculaMonto_Cupones ()
Metodo CalculaMonto_Cupones, calcula el total de dinero por los cupones
Returns
double
Definition at line 120 of file Factura.cs.
         {
             double sumatoria = 0.0;
             foreach (Articulo item in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
             {
                 if(item is Articulo_Cupon)
                 sumatoria += item.Precio;
             }
             return sumatoria;
         }
References Capa_Entidades.Clases.Pedido._ListaArticulosComprados, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Pago._Pedido, and Capa_Entidades.Clases.Articulo.Precio.
Referenced by Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Adicionales(), and Capa_Entidades.Clases.Factura.ObtenerXML().
CalculaMonto_Productos()
double Capa_Entidades.Clases.Factura.CalculaMonto_Productos ()
Metodo CalculaMonto_Productos, calcula el total de dinero por los productos
Returns
double
Definition at line 136 of file Factura.cs.
         {
             double sumatoria = 0.0;
             foreach (Articulo item in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
             {
                 if (item is Articulo_Producto)
                     sumatoria += item.Precio;
             }
             return sumatoria;
         }
References Capa_Entidades.Clases.Pedido._ListaArticulosComprados, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Pago._Pedido, and Capa_Entidades.Clases.Articulo.Precio.
Referenced by Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Productos(), and Capa_Entidades.Clases.Factura.ObtenerXML().
CalculaMonto_Total()
double Capa_Entidades.Clases.Factura.CalculaMonto_Total ()
Metodo CalculaMonto_Total, calcula el total de la factura
Returns
double
Definition at line 83 of file Factura.cs.
         {
             return Calcula_SubTotal() + Calcula_IVA();
         }
References Capa_Entidades.Clases.Factura.Calcula_IVA(), and Capa_Entidades.Clases.Factura.Calcula_SubTotal().
Referenced by Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Total(), Capa_Entidades.Clases.Factura.ObtenerPDF(), Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Clases.Factura.ObtenerXML().
CalculaMonto_Total_Dolares()
double Capa_Entidades.Clases.Factura.CalculaMonto_Total_Dolares ()
Metodo CalculaMonto_Total_Dolares, calcula el total de la factura en dolares
Returns
double
Definition at line 101 of file Factura.cs.
         {
             return (Calcula_SubTotal() + Calcula_IVA())/_PagoUsuarioCliente._Moneda.ValorCompra;
         }
References Capa_Entidades.Clases.Pago._Moneda, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Factura.Calcula_IVA(), Capa_Entidades.Clases.Factura.Calcula_SubTotal(), and Capa_Entidades.Clases.Moneda.ValorCompra.
Referenced by Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Total_Dolares(), Capa_Entidades.Clases.Factura.ObtenerPDF(), and Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada().
CalculaMonto_Total_SinEnvio()
double Capa_Entidades.Clases.Factura.CalculaMonto_Total_SinEnvio ()
Metodo CalculaMonto_Total_SinEnvio, calcula el total de la factura sin el envio
Returns
double
Definition at line 110 of file Factura.cs.
         {
             return Calcula_SubTotal_Gravado()+Calcula_IVA();
         }
References Capa_Entidades.Clases.Factura.Calcula_IVA(), and Capa_Entidades.Clases.Factura.Calcula_SubTotal_Gravado().
Referenced by Capa_Entidades.Clases.Factura.ObtenerPDF(), and Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada().
CalculaMonto_Total_SoloConIVA()
double Capa_Entidades.Clases.Factura.CalculaMonto_Total_SoloConIVA ()
Metodo CalculaMonto_Total_SoloConIVA, calcula el total de la factura
Returns
double
Definition at line 92 of file Factura.cs.
         {
             return Calcula_SubTotal_Gravado() + Calcula_IVA();
         }
References Capa_Entidades.Clases.Factura.Calcula_IVA(), and Capa_Entidades.Clases.Factura.Calcula_SubTotal_Gravado().
ObtenerPDF()
void Capa_Entidades.Clases.Factura.ObtenerPDF ()
Metodo que genera el PDF de Factura
Returns
void
Definition at line 309 of file Factura.cs.
         {
             List<int> Repeticiones = new List<int>();
             //CREA EL DOCUMENTO
             Document doc = new Document(iTextSharp.text.PageSize.LETTER);
             //    Document doc = new Document(iTextSharp.text.PageSize.A4.Rotate());
             //TIPOS DE LETRA QUE VAMOS USAR
             BaseFont arial = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
             iTextSharp.text.Font f_15_bold = new iTextSharp.text.Font(arial, 13, iTextSharp.text.Font.BOLD);
             iTextSharp.text.Font f_12_normal = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.NORMAL);
             iTextSharp.text.Font f_12_normal_ColorRed = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.NORMAL, BaseColor.RED);
             iTextSharp.text.Font f_12_normal_ColorWhite = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.NORMAL, BaseColor.WHITE);
             iTextSharp.text.Font f_12_bold = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.BOLD);
             Random rnd = new Random();
             int numeroRnd = rnd.Next(1762, 10000);
             //RUTA DONDE SE VA GUARDAR EL DOCUMENTO PDF
             FileStream os = new FileStream(@"c:\temp\FacturaCompra.pdf", FileMode.Create);
             using (os)
             {
                 PdfWriter.GetInstance(doc, os);//DEFINIMOS QUE DOCUMENTO VAMOS USAR
                 doc.Open();// LO ABRIMOS
                 AgregaImagenPDF(doc, @"..\..\imagen\pngegg.png");
                 #region INFORMACION DE COMPANNIA
                 //INFORMACION DE LA COMAPNNIA
                 PdfPTable table1 = new PdfPTable(1);
                 float[] width = new float[] { 40f, 60f };
                 PdfPCell cel1 = new PdfPCell(new Phrase(_UsuarioComercio.Nombre, f_15_bold));
                 PdfPCell cel2 = new PdfPCell(new Phrase(_UsuarioComercio.Identificacion.ToString(), f_15_bold));
                 PdfPCell cel3 = new PdfPCell(new Phrase(_UsuarioComercio._Direccion.DescripcionUbicacion, f_12_normal));
                 PdfPCell cel4 = new PdfPCell(new Phrase("Correo Electronico:"+_UsuarioComercio.CorreoElectronico
                     +" \nTelefono :"+_UsuarioComercio.NumeroTelefono+"\n", f_12_normal));
                 //DEFINE EL ESTILO CON EL CUAL SE DESPLEGARA
                 cel1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel3.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel4.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 //DEFINE LA POSICION DONDE SE DESPLEGARA
                 cel1.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel2.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel3.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel4.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 //DEFINE ESTILO Y POSISICION DONDE COLOCAREMOS NUESTRA TABLA 1
                 table1.WidthPercentage = 70;// ancho de la caja
                 table1.HorizontalAlignment = Element.ALIGN_LEFT;
                 table1.AddCell(cel1);
                 table1.AddCell(cel2);
                 table1.AddCell(cel3);
                 table1.AddCell(cel4);
                 table1.SpacingAfter = 15;//espacio hacia la siguiente estructura
                 table1.SpacingBefore = 20;
                 // WriteWaterMark(doc, @"..\..\imagen\final.png");
                 doc.Add(table1);//se agrega la tabla al documento
                 #endregion
                 #region INFORMACION DE CLIENTE
                 table1 = new PdfPTable(1);
                 cel4 = new PdfPCell(new Phrase("INFORMACION DEL CLIENTE", f_12_bold));
                 cel1 = new PdfPCell(new Phrase("Identificacion: "+_UsuarioCliente.Identificacion.ToString(), f_12_normal));
                 cel2 = new PdfPCell(new Phrase("Nombre Completo: "+ _UsuarioCliente.Nombre+" "+(_UsuarioCliente as Usuario_Cliente).Apellido, f_12_normal));
                 cel3 = new PdfPCell(new Phrase("Numero de telefono: "+_UsuarioCliente.NumeroTelefono, f_12_normal));
                 PdfPCell cel7 = new PdfPCell(new Phrase("Correo electronico: " + _UsuarioCliente.CorreoElectronico, f_12_normal));
                 PdfPCell cel8 = new PdfPCell(new Phrase("Direccion fisica: " + _UsuarioCliente._Direccion.DescripcionUbicacion, f_12_normal));
                 cel1.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel2.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel3.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel4.HorizontalAlignment = Element.ALIGN_TOP;
                 cel7.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel8.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel3.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel7.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel8.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 //     cel4.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel4.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel4);
                 table1.AddCell(cel1);
                 table1.AddCell(cel2);
                 table1.AddCell(cel3);
                 table1.AddCell(cel7);
                 table1.AddCell(cel8);
                 table1.SpacingAfter = 20;
                 //  table1.SpacingBefore = 10;
                 table1.WidthPercentage = 40;
                 PdfPTable table2 = new PdfPTable(1);
                 table2.AddCell(table1);
                 table2.HorizontalAlignment = Element.ALIGN_RIGHT;
                 //  table1.WidthPercentage = 40;
                 doc.Add(table2);
                 #endregion
                 #region INFORMACION DE LA FACTURA
                 iTextSharp.text.Paragraph parrafo = new iTextSharp.text.Paragraph(new Phrase("Fecha de venta: " + DateTime.Now.ToString() + "\n", f_12_normal));
                 //   parrafo.Add(new Phrase("Fecha de venta: " + DateTime.Now.Date.ToString() + "\n", f_12_normal));
                 parrafo.Add(new Phrase("Numero de factura N°"+ numeroRnd.ToString()+ "", f_15_bold));
                 parrafo.Alignment = Element.ALIGN_JUSTIFIED;
                 doc.Add(parrafo);
                 #endregion
                 #region LISTA DE PRODUCTOS
                 table1 = new PdfPTable(5);//5 NUMERO DE LAS COLUMNAS QUE SE VAN UTILIZAR
                 //COLUMNAS DE LA TABLA
                 cel1 = new PdfPCell(new Phrase("CODIGO", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("NOMBRE", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("CANT", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("PRC UND", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("PRC TT", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 //CALCULA LA CANTIDAD DE ARTICULOS POR CADA UNO, FUERON COMPRADOS
                 int repeticiones = 0;
                 List<Articulo> art = new List<Articulo>();
                 foreach (Articulo item in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
                 {
                     foreach (Articulo itemAux in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
                     {
                         if(item.Identificacion == itemAux.Identificacion)
{
                             repeticiones++;
                         }
                     }
                     Articulo a = item;
                     a.Cantidad = repeticiones;
                     art.Add(a);
                     repeticiones = 0;
                 }
                 int x = 0;
                 foreach (Articulo item in art.Distinct())
                 {
                     cel1 = new PdfPCell(new Phrase(item.Identificacion.ToString()));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase(item.Nombre));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase(item.Cantidad.ToString()));
                     cel1.HorizontalAlignment = Element.ALIGN_CENTER;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase("₡" + item.Precio.ToString("#,###,###.00") ));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase("₡"+(item.Precio * item.Cantidad).ToString("#,###,###.00") ));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     x++;
                 }
                 table1.WidthPercentage = 100;
                 width = new float[] { 100f, 400f, 100f, 115, 125 };
                 table1.SetWidths(width);
                 table1.SpacingBefore = 20;
                 doc.Add(table1);
                 //TOTAL
                 table1 = new PdfPTable(2);
                 cel1 = new PdfPCell(new Phrase("SubTotal Gravado: ", f_12_bold));
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 cel2 = new PdfPCell(new Phrase("₡"+Calcula_SubTotal_Gravado().ToString("#,###,###.00"), f_12_normal));
                 cel7 = new PdfPCell(new Phrase("Descuento Gravado: ", f_12_bold));
                 cel7.BackgroundColor = BaseColor.LIGHT_GRAY;
                 cel8 = new PdfPCell(new Phrase("₡0.00"  , f_12_normal));
                 cel3 = new PdfPCell(new Phrase("Impuestos: ", f_12_bold));
                 cel3.BackgroundColor = BaseColor.LIGHT_GRAY;
                 cel4 = new PdfPCell(new Phrase("₡" + Calcula_IVA().ToString("#,###,###.00"), f_12_normal));
                 PdfPCell cel9 = new PdfPCell(new Phrase("Total: ", f_12_bold));
                 cel9.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel10 = new PdfPCell(new Phrase("₡" + CalculaMonto_Total_SinEnvio().ToString("#,###,###.00"), f_12_normal));
                 PdfPCell cel11 = new PdfPCell(new Phrase("Otros: ", f_12_bold));
                 cel11.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel12 = new PdfPCell(new Phrase("₡" + Calcula_Envio().ToString("#,###,###.00"), f_12_normal));
                 PdfPCell cel5 = new PdfPCell(new Phrase("Total a Pagar Colones: ", f_12_bold));
                 cel5.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel6 = new PdfPCell(new Phrase("₡" + CalculaMonto_Total().ToString("#,###,###.00"), f_12_normal_ColorRed));
                 PdfPCell cel13 = new PdfPCell(new Phrase("Total a Pagar Dolares: ", f_12_bold));
                 cel13.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel14 = new PdfPCell(new Phrase( CalculaMonto_Total_Dolares().ToString("#,###,###.00"), f_12_normal_ColorRed));
                 table1.WidthPercentage = 100;
                 width = new float[] { 165, 50 };
                 cel1.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel1.FixedHeight = 20;
                 cel3.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel3.FixedHeight = 20;
                 cel5.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel5.FixedHeight = 20;
                 cel7.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel7.FixedHeight = 20;
                 cel9.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel9.FixedHeight = 20;
                 cel11.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel11.FixedHeight = 20;
                 cel13.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel13.FixedHeight = 20;
                 cel2.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel4.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel6.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel8.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel10.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel12.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel6.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel14.HorizontalAlignment = Element.ALIGN_LEFT;
                 table1.SetWidths(width);
                 table1.AddCell(cel1);
                 table1.AddCell(cel2);
                 table1.AddCell(cel7);
                 table1.AddCell(cel8);
                 table1.AddCell(cel3);
                 table1.AddCell(cel4);
                 table1.AddCell(cel9);
                 table1.AddCell(cel10);
                 table1.AddCell(cel11);
                 table1.AddCell(cel12);
                 table1.AddCell(cel5);
                 table1.AddCell(cel6);
                 table1.AddCell(cel13);
                 table1.AddCell(cel14);
                 table1.SpacingAfter = 10;
                 doc.Add(table1);
                 #endregion
                 string xmlGenerado = ObtenerXML();
                 string xmlCifrado = Utilitarios.ComputeSha256Hash(xmlGenerado);
                 parrafo = new iTextSharp.text.Paragraph(new Phrase("Codigo de XML enviado cifrado:\n " + xmlCifrado+" \n", f_12_normal));
                 parrafo.Add(new Phrase("\nAutorizada mediante resolución Nº DGT - R - 48 - 2016 del 7 de octubre de 2016\n", f_12_normal));
                 parrafo.Alignment = Element.ALIGN_JUSTIFIED;
                 doc.Add(parrafo);
                 doc.Close();//CERRAMOS EL DOCUMENTO
             }
         }
References Capa_Entidades.Clases.Usuario._Direccion, Capa_Entidades.Clases.Pedido._ListaArticulosComprados, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Pago._Pedido, Capa_Entidades.Clases.Factura._UsuarioCliente, Capa_Entidades.Clases.Factura._UsuarioComercio, Capa_Entidades.Clases.Factura.AgregaImagenPDF(), Capa_Entidades.Clases.Factura.Calcula_Envio(), Capa_Entidades.Clases.Factura.Calcula_IVA(), Capa_Entidades.Clases.Factura.Calcula_SubTotal_Gravado(), Capa_Entidades.Clases.Factura.CalculaMonto_Total(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_Dolares(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_SinEnvio(), Capa_Entidades.Clases.Articulo.Cantidad, Utilitarios.ComputeSha256Hash(), Capa_Entidades.Clases.Usuario.CorreoElectronico, Capa_Entidades.Clases.Direccion.DescripcionUbicacion, Capa_Entidades.Clases.Usuario.Identificacion, Capa_Entidades.Clases.Articulo.Identificacion, Capa_Entidades.Clases.Articulo.Nombre, Capa_Entidades.Clases.Usuario.Nombre, Capa_Entidades.Clases.Usuario.NumeroTelefono, Capa_Entidades.Clases.Factura.ObtenerXML(), and Capa_Entidades.Clases.Articulo.Precio.
Referenced by Capa_Entidades.Gestor.Gestor_Factura.ObtenerPDF().
ObtenerPDF_GuardadoEnRutaSeleccionada()
void Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada (string pRuta)
Metodo que genera el PDF de Factura, y lo guarda en la ruta especificada por el usuario
Returns
void
Definition at line 619 of file Factura.cs.
         {
             List<int> Repeticiones = new List<int>();
             //CREA EL DOCUMENTO
             Document doc = new Document(iTextSharp.text.PageSize.LETTER);
             //    Document doc = new Document(iTextSharp.text.PageSize.A4.Rotate());
             //TIPOS DE LETRA QUE VAMOS USAR
             BaseFont arial = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
             iTextSharp.text.Font f_15_bold = new iTextSharp.text.Font(arial, 13, iTextSharp.text.Font.BOLD);
             iTextSharp.text.Font f_12_normal = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.NORMAL);
             iTextSharp.text.Font f_12_normal_ColorRed = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.NORMAL, BaseColor.RED);
             iTextSharp.text.Font f_12_normal_ColorWhite = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.NORMAL, BaseColor.WHITE);
             iTextSharp.text.Font f_12_bold = new iTextSharp.text.Font(arial, 12, iTextSharp.text.Font.BOLD);
             Random rnd = new Random();
             int numeroRnd = rnd.Next(1762, 10000);
             //RUTA DONDE SE VA GUARDAR EL DOCUMENTO PDF
             FileStream os = new FileStream(pRuta, FileMode.Create);
             using (os)
             {
                 PdfWriter.GetInstance(doc, os);//DEFINIMOS QUE DOCUMENTO VAMOS USAR
                 doc.Open();// LO ABRIMOS
                 AgregaImagenPDF(doc, @"..\..\imagen\pngegg.png");
                 #region INFORMACION DE COMPANNIA
                 //INFORMACION DE LA COMAPNNIA
                 PdfPTable table1 = new PdfPTable(1);
                 float[] width = new float[] { 40f, 60f };
                 PdfPCell cel1 = new PdfPCell(new Phrase(_UsuarioComercio.Nombre, f_15_bold));
                 PdfPCell cel2 = new PdfPCell(new Phrase(_UsuarioComercio.Identificacion.ToString(), f_15_bold));
                 PdfPCell cel3 = new PdfPCell(new Phrase(_UsuarioComercio._Direccion.DescripcionUbicacion, f_12_normal));
                 PdfPCell cel4 = new PdfPCell(new Phrase("Correo Electronico:" + _UsuarioComercio.CorreoElectronico
                     + " \nTelefono :" + _UsuarioComercio.NumeroTelefono + "\n", f_12_normal));
                 //DEFINE EL ESTILO CON EL CUAL SE DESPLEGARA
                 cel1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel3.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel4.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 //DEFINE LA POSICION DONDE SE DESPLEGARA
                 cel1.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel2.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel3.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel4.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 //DEFINE ESTILO Y POSISICION DONDE COLOCAREMOS NUESTRA TABLA 1
                 table1.WidthPercentage = 70;// ancho de la caja
                 table1.HorizontalAlignment = Element.ALIGN_LEFT;
                 table1.AddCell(cel1);
                 table1.AddCell(cel2);
                 table1.AddCell(cel3);
                 table1.AddCell(cel4);
                 table1.SpacingAfter = 15;//espacio hacia la siguiente estructura
                 table1.SpacingBefore = 20;
                 // WriteWaterMark(doc, @"..\..\imagen\final.png");
                 doc.Add(table1);//se agrega la tabla al documento
                 #endregion
                 #region INFORMACION DE CLIENTE
                 table1 = new PdfPTable(1);
                 cel4 = new PdfPCell(new Phrase("INFORMACION DEL CLIENTE", f_12_bold));
                 cel1 = new PdfPCell(new Phrase("Identificacion: " + _UsuarioCliente.Identificacion.ToString(), f_12_normal));
                 cel2 = new PdfPCell(new Phrase("Nombre Completo: " + _UsuarioCliente.Nombre + " " + (_UsuarioCliente as Usuario_Cliente).Apellido, f_12_normal));
                 cel3 = new PdfPCell(new Phrase("Numero de telefono: " + _UsuarioCliente.NumeroTelefono, f_12_normal));
                 PdfPCell cel7 = new PdfPCell(new Phrase("Correo electronico: " + _UsuarioCliente.CorreoElectronico, f_12_normal));
                 PdfPCell cel8 = new PdfPCell(new Phrase("Direccion fisica: " + _UsuarioCliente._Direccion.DescripcionUbicacion, f_12_normal));
                 cel1.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel2.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel3.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel4.HorizontalAlignment = Element.ALIGN_TOP;
                 cel7.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel8.HorizontalAlignment = Element.ALIGN_JUSTIFIED;
                 cel1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel3.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel7.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel8.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 //     cel4.Border = iTextSharp.text.Rectangle.NO_BORDER;
                 cel4.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel4);
                 table1.AddCell(cel1);
                 table1.AddCell(cel2);
                 table1.AddCell(cel3);
                 table1.AddCell(cel7);
                 table1.AddCell(cel8);
                 table1.SpacingAfter = 20;
                 //  table1.SpacingBefore = 10;
                 table1.WidthPercentage = 40;
                 PdfPTable table2 = new PdfPTable(1);
                 table2.AddCell(table1);
                 table2.HorizontalAlignment = Element.ALIGN_RIGHT;
                 //  table1.WidthPercentage = 40;
                 doc.Add(table2);
                 #endregion
                 #region INFORMACION DE LA FACTURA
                 iTextSharp.text.Paragraph parrafo = new iTextSharp.text.Paragraph(new Phrase("Fecha de venta: " + DateTime.Now.ToString() + "\n", f_12_normal));
                 //   parrafo.Add(new Phrase("Fecha de venta: " + DateTime.Now.Date.ToString() + "\n", f_12_normal));
                 parrafo.Add(new Phrase("Numero de factura N°" + numeroRnd.ToString() + "", f_15_bold));
                 parrafo.Alignment = Element.ALIGN_JUSTIFIED;
                 doc.Add(parrafo);
                 #endregion
                 #region LISTA DE PRODUCTOS
                 table1 = new PdfPTable(5);//5 NUMERO DE LAS COLUMNAS QUE SE VAN UTILIZAR
                 //COLUMNAS DE LA TABLA
                 cel1 = new PdfPCell(new Phrase("CODIGO", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("NOMBRE", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("CANT", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("PRC UND", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 cel1 = new PdfPCell(new Phrase("PRC TT", f_12_bold));
                 cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel1.FixedHeight = 20;
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 table1.AddCell(cel1);
                 //CALCULA LA CANTIDAD DE ARTICULOS POR CADA UNO, FUERON COMPRADOS
                 int repeticiones = 0;
                 List<Articulo> art = new List<Articulo>();
                 foreach (Articulo item in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
                 {
                     foreach (Articulo itemAux in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
                     {
                         if (item.Identificacion == itemAux.Identificacion)
{
                             repeticiones++;
                         }
                     }
                     Articulo a = item;
                     a.Cantidad = repeticiones;
                     art.Add(a);
                     repeticiones = 0;
                 }
                 int x = 0;
                 foreach (Articulo item in art.Distinct())
                 {
                     cel1 = new PdfPCell(new Phrase(item.Identificacion.ToString()));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase(item.Nombre));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase(item.Cantidad.ToString()));
                     cel1.HorizontalAlignment = Element.ALIGN_CENTER;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase("₡" + item.Precio.ToString("#,###,###.00")));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     cel1 = new PdfPCell(new Phrase("₡" + (item.Precio * item.Cantidad).ToString("#,###,###.00")));
                     cel1.HorizontalAlignment = Element.ALIGN_LEFT;
                     cel1.FixedHeight = 20;
                     table1.AddCell(cel1);
                     x++;
                 }
                 table1.WidthPercentage = 100;
                 width = new float[] { 100f, 400f, 100f, 115, 125 };
                 table1.SetWidths(width);
                 table1.SpacingBefore = 20;
                 doc.Add(table1);
                 //TOTAL
                 table1 = new PdfPTable(2);
                 cel1 = new PdfPCell(new Phrase("SubTotal Gravado: ", f_12_bold));
                 cel1.BackgroundColor = BaseColor.LIGHT_GRAY;
                 cel2 = new PdfPCell(new Phrase("¢" + Calcula_SubTotal_Gravado().ToString("#,###,###.00"), f_12_normal));
                 cel7 = new PdfPCell(new Phrase("Descuento Gravado: ", f_12_bold));
                 cel7.BackgroundColor = BaseColor.LIGHT_GRAY;
                 cel8 = new PdfPCell(new Phrase("¢0.00", f_12_normal));
                 cel3 = new PdfPCell(new Phrase("Impuestos: ", f_12_bold));
                 cel3.BackgroundColor = BaseColor.LIGHT_GRAY;
                 cel4 = new PdfPCell(new Phrase("¢" + Calcula_IVA().ToString("#,###,###.00"), f_12_normal));
                 PdfPCell cel9 = new PdfPCell(new Phrase("Total: ", f_12_bold));
                 cel9.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel10 = new PdfPCell(new Phrase( "¢" + CalculaMonto_Total_SinEnvio().ToString("#,###,###.00"), f_12_normal));
                 PdfPCell cel11 = new PdfPCell(new Phrase("Otros: ", f_12_bold));
                 cel11.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel12 = new PdfPCell(new Phrase("¢" + Calcula_Envio().ToString("#,###,###.00"), f_12_normal));
                 PdfPCell cel5 = new PdfPCell(new Phrase("Total a Pagar Colones: ", f_12_bold));
                 cel5.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel6 = new PdfPCell(new Phrase("¢" + CalculaMonto_Total().ToString("#,###,###.00"), f_12_normal_ColorRed));
                 PdfPCell cel13 = new PdfPCell(new Phrase("Total a Pagar Dolares: ", f_12_bold));
                 cel13.BackgroundColor = BaseColor.LIGHT_GRAY;
                 PdfPCell cel14 = new PdfPCell(new Phrase( CalculaMonto_Total_Dolares().ToString("#,###,###.00"), f_12_normal_ColorRed));
                 table1.WidthPercentage = 100;
                 width = new float[] { 165, 50 };
                 cel1.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel1.FixedHeight = 20;
                 cel3.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel3.FixedHeight = 20;
                 cel5.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel5.FixedHeight = 20;
                 cel7.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel7.FixedHeight = 20;
                 cel9.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel9.FixedHeight = 20;
                 cel11.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel11.FixedHeight = 20;
                 cel13.HorizontalAlignment = Element.ALIGN_RIGHT;
                 cel13.FixedHeight = 20;
                 cel2.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel4.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel6.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel8.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel10.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel12.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel6.HorizontalAlignment = Element.ALIGN_LEFT;
                 cel14.HorizontalAlignment = Element.ALIGN_LEFT;
                 table1.SetWidths(width);
                 table1.AddCell(cel1);
                 table1.AddCell(cel2);
                 table1.AddCell(cel7);
                 table1.AddCell(cel8);
                 table1.AddCell(cel3);
                 table1.AddCell(cel4);
                 table1.AddCell(cel9);
                 table1.AddCell(cel10);
                 table1.AddCell(cel11);
                 table1.AddCell(cel12);
                 table1.AddCell(cel5);
                 table1.AddCell(cel6);
                 table1.AddCell(cel13);
                 table1.AddCell(cel14);
                 table1.SpacingAfter = 10;
                 doc.Add(table1);
                 #endregion
                 string xmlGenerado = ObtenerXML();
                 string xmlCifrado = Utilitarios.ComputeSha256Hash(xmlGenerado);
                 parrafo = new iTextSharp.text.Paragraph(new Phrase("Codigo de XML enviado cifrado:\n " + xmlCifrado + " \n", f_12_normal));
                 parrafo.Add(new Phrase("\nAutorizada mediante resolución Nº DGT - R - 48 - 2016 del 7 de octubre de 2016\n", f_12_normal));
                 parrafo.Alignment = Element.ALIGN_JUSTIFIED;
                 doc.Add(parrafo);
                 doc.Close();//CERRAMOS EL DOCUMENTO
             }
         }
References Capa_Entidades.Clases.Usuario._Direccion, Capa_Entidades.Clases.Pedido._ListaArticulosComprados, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Pago._Pedido, Capa_Entidades.Clases.Factura._UsuarioCliente, Capa_Entidades.Clases.Factura._UsuarioComercio, Capa_Entidades.Clases.Factura.AgregaImagenPDF(), Capa_Entidades.Clases.Factura.Calcula_Envio(), Capa_Entidades.Clases.Factura.Calcula_IVA(), Capa_Entidades.Clases.Factura.Calcula_SubTotal_Gravado(), Capa_Entidades.Clases.Factura.CalculaMonto_Total(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_Dolares(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_SinEnvio(), Capa_Entidades.Clases.Articulo.Cantidad, Utilitarios.ComputeSha256Hash(), Capa_Entidades.Clases.Usuario.CorreoElectronico, Capa_Entidades.Clases.Direccion.DescripcionUbicacion, Capa_Entidades.Clases.Usuario.Identificacion, Capa_Entidades.Clases.Articulo.Identificacion, Capa_Entidades.Clases.Articulo.Nombre, Capa_Entidades.Clases.Usuario.Nombre, Capa_Entidades.Clases.Usuario.NumeroTelefono, Capa_Entidades.Clases.Factura.ObtenerXML(), and Capa_Entidades.Clases.Articulo.Precio.
Referenced by Capa_Entidades.Gestor.Gestor_Factura.ObtenerPDF_GuardadoEnRutaSeleccionada().
ObtenerXML()
string Capa_Entidades.Clases.Factura.ObtenerXML ()
Metodo que genera el XML de Factura
Returns
string
Definition at line 197 of file Factura.cs.
         {
             XmlDocument documento = new XmlDocument();
             XmlDeclaration dec = documento.CreateXmlDeclaration("1.0", null, null);
             documento.AppendChild(dec);
             XmlElement raiz = documento.CreateElement("raiz");
             XmlElement facturaElectronica = documento.CreateElement("facturaElectronica");
             XmlElement tributario = documento.CreateElement("tributario");
             XmlElement identificacion = documento.CreateElement("identificacion");
             identificacion.InnerText = _UsuarioComercio.Identificacion.ToString();
             tributario.AppendChild(identificacion);
             XmlElement Nombre = documento.CreateElement("nombre");
             Nombre.InnerText = _UsuarioComercio.Nombre;
             tributario.AppendChild(Nombre);
             XmlElement direccion = documento.CreateElement("direccion");
             direccion.InnerText = _UsuarioComercio._Direccion.DescripcionUbicacion;
             tributario.AppendChild(direccion);
             XmlElement correoElectronico = documento.CreateElement("correoElectronico");
             correoElectronico.InnerText = _UsuarioComercio.CorreoElectronico;
             tributario.AppendChild(correoElectronico);
             facturaElectronica.AppendChild(tributario);
             //NUMERACION CONSECUTIVA ????
             //CLAVE NUMERICA ????
             XmlElement fechaEmision = documento.CreateElement("fechaEmision");
             fechaEmision.InnerText = _PagoUsuarioCliente.FechaPago.ToString("dd/MM/yy hh:mm");
             facturaElectronica.AppendChild(fechaEmision);
             XmlElement condicionVenta = documento.CreateElement("condicionVenta");
             condicionVenta.InnerText = "CONTADO";
             facturaElectronica.AppendChild(condicionVenta);
             XmlElement medioPago = documento.CreateElement("medioPago");
             medioPago.InnerText = "TARJETA";
             facturaElectronica.AppendChild(medioPago);
             XmlElement mercancia = documento.CreateElement("mercancia");
             foreach(Articulo item in _PagoUsuarioCliente._Pedido._ListaArticulosComprados)
             {
                 XmlElement producto = documento.CreateElement("producto");
                 XmlElement codigo = documento.CreateElement("codigo");
                 codigo.InnerText = item.Identificacion;
                 producto.AppendChild(codigo);
                 XmlElement nombre = documento.CreateElement("nombre");
                 nombre.InnerText = item.Nombre;
                 producto.AppendChild(nombre);
                 XmlElement descripcion = documento.CreateElement("descripcion");
                 descripcion.InnerText = item.Descripcion;
                 producto.AppendChild(descripcion);
                 XmlElement precio = documento.CreateElement("precio");
                 precio.InnerText = "₡" + item.Precio.ToString("#,###,###.00");
                 producto.AppendChild(precio);
                 mercancia.AppendChild(producto);
             }
             facturaElectronica.AppendChild(mercancia);
             XmlElement descuento = documento.CreateElement("descuento");
             descuento.InnerText = "₡ 0.00";
             facturaElectronica.AppendChild(descuento);
             XmlElement subtotal = documento.CreateElement("subtotal");
             subtotal.InnerText = "₡ " + Calcula_SubTotal_Gravado().ToString("#,###,###.00");
             facturaElectronica.AppendChild(subtotal);
             XmlElement impuesto = documento.CreateElement("impuesto");
             impuesto.InnerText = "13%" ;
             facturaElectronica.AppendChild(impuesto);
             XmlElement serviciosPrestados = documento.CreateElement("serviciosPrestados");
             serviciosPrestados.InnerText = "₡ " + Calcula_Envio().ToString("#,###,###.00");
             facturaElectronica.AppendChild(serviciosPrestados);
             XmlElement valorMercancias = documento.CreateElement("valorMercancias");
             valorMercancias.InnerText = "₡ " + (CalculaMonto_Cupones() + CalculaMonto_Productos()).ToString("#,###,###.00");
             facturaElectronica.AppendChild(valorMercancias);
             XmlElement precioNeto = documento.CreateElement("precioNeto");
             precioNeto.InnerText = "₡ " + Calcula_SubTotal().ToString("#,###,###.00");
             facturaElectronica.AppendChild(precioNeto);
             XmlElement impuestoVentas = documento.CreateElement("impuestoVentas");
             impuestoVentas.InnerText = "₡ " + Calcula_IVA().ToString("#,###,###.00");
             facturaElectronica.AppendChild(impuestoVentas);
             XmlElement valorTotal = documento.CreateElement("valorTotal");
             valorTotal.InnerText = "₡ " + CalculaMonto_Total().ToString("#,###,###.00");
             facturaElectronica.AppendChild(valorTotal);
             raiz.AppendChild(facturaElectronica);
             documento.AppendChild(raiz);
             return documento.InnerXml;
         }
References Capa_Entidades.Clases.Usuario._Direccion, Capa_Entidades.Clases.Pedido._ListaArticulosComprados, Capa_Entidades.Clases.Factura._PagoUsuarioCliente, Capa_Entidades.Clases.Pago._Pedido, Capa_Entidades.Clases.Factura._UsuarioComercio, Capa_Entidades.Clases.Factura.Calcula_Envio(), Capa_Entidades.Clases.Factura.Calcula_IVA(), Capa_Entidades.Clases.Factura.Calcula_SubTotal(), Capa_Entidades.Clases.Factura.Calcula_SubTotal_Gravado(), Capa_Entidades.Clases.Factura.CalculaMonto_Cupones(), Capa_Entidades.Clases.Factura.CalculaMonto_Productos(), Capa_Entidades.Clases.Factura.CalculaMonto_Total(), Capa_Entidades.Clases.Usuario.CorreoElectronico, Capa_Entidades.Clases.Articulo.Descripcion, Capa_Entidades.Clases.Direccion.DescripcionUbicacion, Capa_Entidades.Clases.Pago.FechaPago, Capa_Entidades.Clases.Usuario.Identificacion, Capa_Entidades.Clases.Articulo.Identificacion, Capa_Entidades.Clases.Articulo.Nombre, Capa_Entidades.Clases.Usuario.Nombre, and Capa_Entidades.Clases.Articulo.Precio.
Referenced by Capa_Entidades.Clases.Factura.ObtenerPDF(), Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Gestor.Gestor_Factura.ObtenerXML().
SetCulture()
void Capa_Entidades.Clases.Factura.SetCulture ()
Metodo que setea la cultura de la clase
Returns
void
Definition at line 946 of file Factura.cs.
         {
             // Colocar Cultura Estandar para Costa Rica
             CultureInfo Micultura = new CultureInfo("es-CR", false);
             Micultura.NumberFormat.CurrencySymbol = "¢";
             Micultura.NumberFormat.CurrencyDecimalDigits = 2;
             Micultura.NumberFormat.CurrencyDecimalSeparator = ".";
             Micultura.NumberFormat.CurrencyGroupSeparator = ",";
             int[] grupo = new int[] { 3, 3, 3 };
             Micultura.NumberFormat.CurrencyGroupSizes = grupo;
             Micultura.NumberFormat.NumberDecimalDigits = 2;
             Micultura.NumberFormat.NumberGroupSeparator = ",";
             Micultura.NumberFormat.NumberDecimalSeparator = ".";
             Micultura.NumberFormat.NumberGroupSizes = grupo;
             Thread.CurrentThread.CurrentCulture = Micultura;
         }
Member Data Documentation
_PagoUsuarioCliente
Pago Capa_Entidades.Clases.Factura._PagoUsuarioCliente = null
_PagoUsuarioCliente
Pago que contiene el pedido del cliente
Definition at line 30 of file Factura.cs.
Referenced by Capa_Entidades.Clases.Factura.Calcula_Envio(), Capa_Entidades.Clases.Factura.Calcula_SubTotal(), Capa_Entidades.Clases.Factura.Calcula_SubTotal_Gravado(), Capa_Entidades.Clases.Factura.CalculaMonto_Cupones(), Capa_Entidades.Clases.Factura.CalculaMonto_Productos(), Capa_Entidades.Clases.Factura.CalculaMonto_Total_Dolares(), Capa_Entidades.Clases.Factura.ObtenerPDF(), Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Clases.Factura.ObtenerXML().
_UsuarioCliente
Usuario Capa_Entidades.Clases.Factura._UsuarioCliente = null
_UsuarioCliente
Usuario cliente
Definition at line 26 of file Factura.cs.
Referenced by Capa_Entidades.Clases.Factura.ObtenerPDF(), and Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada().
_UsuarioComercio
Usuario Capa_Entidades.Clases.Factura._UsuarioComercio = null
_UsuarioComercio
Usuario Comercio
Definition at line 34 of file Factura.cs.
Referenced by Capa_Entidades.Clases.Factura.ObtenerPDF(), Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Clases.Factura.ObtenerXML().
The documentation for this class was generated from the following file:
E:/VisualProyectos/PROYECTOS FINALES PROGRAMADOS UTN/UTN 5CT C# _ AppUberEats/CAPAS/Capa_Logica/Clases/Factura.cs