JustEat Proyecto Final Programado: Capa_Entidades.Gestor.Gestor_Factura Class Reference
Capa_Entidades.Gestor.Gestor_Factura Class Reference
Clase Gestor_Factura, se encarga de obtener los metodos de Factura
Public Member Functions
Gestor_Factura ()
Constructor de clase, que recibe Factura, para asi construir el objeto oFactura
void AsignaCliente (Usuario pCliente)
Metodo que obtiene AsignaCliente, asigna el Cliente
void AsignaPagoCliente (Pago pPago)
Metodo que obtiene AsignaCliente, asigna el Pago
void AsignaComercio (Usuario pComercio)
Metodo que obtiene AsignaCliente, asigna el Comercio
Factura GetInstanceFactura ()
Metodo que devuelve la instancia de factura
double CalculaMonto_Total ()
Metodo que obtieneCalculaMonto_Total, calcula el total de la factura
double CalculaMonto_Total_Dolares ()
Metodo CalculaMonto_Total_Dolares, calcula el total de la factura en dolares
double CalculaMonto_Adicionales ()
Metodo que obtiene CalculaMonto_Adicionales, calcula el total de dinero por los adicionales
double CalculaMonto_Productos ()
Metodo que obtiene CalculaMonto_Productos, calcula el total de dinero por los productos
double Calcula_IVA ()
Metodo que obtiene Calcula_IVA
double Calcula_SubTotal ()
Metodo Calcula_SubTotal, calcula monto sin IVA
double Calcula_Envio ()
Metodo Calcula_Envio, calcula coste del envio
string ObtenerXML ()
Metodo que obtiene el XML de Factura
void ObtenerPDF ()
Metodo que obtiene el PDF de Factura
void ObtenerPDF_GuardadoEnRutaSeleccionada (string pRuta)
Metodo que genera el PDF de Factura, y lo guarda en la ruta especificada por el usuario
Private Attributes
Factura oFactura = null
oFactura
Detailed Description
Clase Gestor_Factura, se encarga de obtener los metodos de Factura
Definition at line 13 of file Gestor_Factura.cs.
Constructor & Destructor Documentation
Gestor_Factura()
Capa_Entidades.Gestor.Gestor_Factura.Gestor_Factura ()
Constructor de clase, que recibe Factura, para asi construir el objeto oFactura
Definition at line 24 of file Gestor_Factura.cs.
         {
             this.oFactura = new Factura();
         }
Member Function Documentation
AsignaCliente()
void Capa_Entidades.Gestor.Gestor_Factura.AsignaCliente (Usuario pCliente)
Metodo que obtiene AsignaCliente, asigna el Cliente
Returns
void
Definition at line 36 of file Gestor_Factura.cs.
         {
             oFactura.AsignaCliente(pCliente);
         }
AsignaComercio()
void Capa_Entidades.Gestor.Gestor_Factura.AsignaComercio (Usuario pComercio)
Metodo que obtiene AsignaCliente, asigna el Comercio
Returns
void
Definition at line 56 of file Gestor_Factura.cs.
         {
             oFactura.AsignaComercio(pComercio);
         }
References Capa_Entidades.Clases.Factura.AsignaComercio(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
AsignaPagoCliente()
void Capa_Entidades.Gestor.Gestor_Factura.AsignaPagoCliente (Pago pPago)
Metodo que obtiene AsignaCliente, asigna el Pago
Returns
void
Definition at line 46 of file Gestor_Factura.cs.
         {
             oFactura.AsignaPagoCliente(pPago);
         }
References Capa_Entidades.Clases.Factura.AsignaPagoCliente(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
Calcula_Envio()
double Capa_Entidades.Gestor.Gestor_Factura.Calcula_Envio ()
Metodo Calcula_Envio, calcula coste del envio
Returns
double
Definition at line 134 of file Gestor_Factura.cs.
         {
             return oFactura.Calcula_Envio();
         }
References Capa_Entidades.Clases.Factura.Calcula_Envio(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
Calcula_IVA()
double Capa_Entidades.Gestor.Gestor_Factura.Calcula_IVA ()
Metodo que obtiene Calcula_IVA
Returns
double
Definition at line 116 of file Gestor_Factura.cs.
         {
             return oFactura.Calcula_IVA();
         }
References Capa_Entidades.Clases.Factura.Calcula_IVA(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
Calcula_SubTotal()
double Capa_Entidades.Gestor.Gestor_Factura.Calcula_SubTotal ()
Metodo Calcula_SubTotal, calcula monto sin IVA
Returns
double
Definition at line 125 of file Gestor_Factura.cs.
         {
             return oFactura.Calcula_SubTotal();
         }
References Capa_Entidades.Clases.Factura.Calcula_SubTotal(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
CalculaMonto_Adicionales()
double Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Adicionales ()
Metodo que obtiene CalculaMonto_Adicionales, calcula el total de dinero por los adicionales
Returns
double
Definition at line 96 of file Gestor_Factura.cs.
         {
             return oFactura.CalculaMonto_Cupones();
         }
References Capa_Entidades.Clases.Factura.CalculaMonto_Cupones(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
CalculaMonto_Productos()
double Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Productos ()
Metodo que obtiene CalculaMonto_Productos, calcula el total de dinero por los productos
Returns
double
Definition at line 107 of file Gestor_Factura.cs.
         {
             return oFactura.CalculaMonto_Productos();
         }
References Capa_Entidades.Clases.Factura.CalculaMonto_Productos(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
CalculaMonto_Total()
double Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Total ()
Metodo que obtieneCalculaMonto_Total, calcula el total de la factura
Returns
double
Definition at line 76 of file Gestor_Factura.cs.
         {
             return oFactura.CalculaMonto_Total();
         }
References Capa_Entidades.Clases.Factura.CalculaMonto_Total(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
CalculaMonto_Total_Dolares()
double Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Total_Dolares ()
Metodo CalculaMonto_Total_Dolares, calcula el total de la factura en dolares
Returns
double
Definition at line 85 of file Gestor_Factura.cs.
         {
             return oFactura.CalculaMonto_Total_Dolares();
         }
References Capa_Entidades.Clases.Factura.CalculaMonto_Total_Dolares(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
GetInstanceFactura()
Factura Capa_Entidades.Gestor.Gestor_Factura.GetInstanceFactura ()
Metodo que devuelve la instancia de factura
Returns
Factura
Definition at line 65 of file Gestor_Factura.cs.
         {
             return oFactura;
         }
References Capa_Entidades.Gestor.Gestor_Factura.oFactura.
ObtenerPDF()
void Capa_Entidades.Gestor.Gestor_Factura.ObtenerPDF ()
Metodo que obtiene el PDF de Factura
Returns
string
Definition at line 155 of file Gestor_Factura.cs.
         {
             oFactura.ObtenerPDF();
         }
References Capa_Entidades.Clases.Factura.ObtenerPDF(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
ObtenerPDF_GuardadoEnRutaSeleccionada()
void Capa_Entidades.Gestor.Gestor_Factura.ObtenerPDF_GuardadoEnRutaSeleccionada (string pRuta)
Metodo que genera el PDF de Factura, y lo guarda en la ruta especificada por el usuario
Returns
void
Definition at line 164 of file Gestor_Factura.cs.
         {
             oFactura.ObtenerPDF_GuardadoEnRutaSeleccionada(pRuta);
         }
References Capa_Entidades.Clases.Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
ObtenerXML()
string Capa_Entidades.Gestor.Gestor_Factura.ObtenerXML ()
Metodo que obtiene el XML de Factura
Returns
string
Definition at line 146 of file Gestor_Factura.cs.
         {
             return oFactura.ObtenerXML();
         }
References Capa_Entidades.Clases.Factura.ObtenerXML(), and Capa_Entidades.Gestor.Gestor_Factura.oFactura.
Member Data Documentation
oFactura
Factura Capa_Entidades.Gestor.Gestor_Factura.oFactura = null private
oFactura
instancia de Factura
Definition at line 18 of file Gestor_Factura.cs.
Referenced by Capa_Entidades.Gestor.Gestor_Factura.AsignaComercio(), Capa_Entidades.Gestor.Gestor_Factura.AsignaPagoCliente(), Capa_Entidades.Gestor.Gestor_Factura.Calcula_Envio(), Capa_Entidades.Gestor.Gestor_Factura.Calcula_IVA(), Capa_Entidades.Gestor.Gestor_Factura.Calcula_SubTotal(), Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Adicionales(), Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Productos(), Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Total(), Capa_Entidades.Gestor.Gestor_Factura.CalculaMonto_Total_Dolares(), Capa_Entidades.Gestor.Gestor_Factura.GetInstanceFactura(), Capa_Entidades.Gestor.Gestor_Factura.ObtenerPDF(), Capa_Entidades.Gestor.Gestor_Factura.ObtenerPDF_GuardadoEnRutaSeleccionada(), and Capa_Entidades.Gestor.Gestor_Factura.ObtenerXML().
The documentation for this class was generated from the following file:
E:/VisualProyectos/PROYECTOS FINALES PROGRAMADOS UTN/UTN 5CT C# _ AppUberEats/CAPAS/Capa_Logica/Gestor/Gestor_Factura.cs